name: CD
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CD
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 'loadbalancing.fresto.top'
          username: 'elkoaditya'
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script:
            cd /var/www/loadbalancing.fresto.top
            git pull origin main
            git status
            service nginx restart