name: CD
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: '34.101.112.211'
          username: ${{ secrets.FTP_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            apt install git
            cd /var/www/html
            git init
            git remote add origin https://github.com/elkoaditya/testload.git
            git pull origin main --allow-unrelated-histories
            service nginx restart