name: CD
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 'loadbalancing.fresto.top'
          username: 'root'
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script:
            whoami
            ls